# Generated by Django 4.2.7 on 2025-11-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='password',
            field=models.CharField(help_text='Password required to unlock this project', max_length=128),
        ),
    ]
